# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bernardo Sá Martins
#email: bsamartins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some technology bits and bytes. A sort of a personal archive
baseurl: "" # the subpath of your site, e.g. /blog
url: http://bsamartins.github.io # the base hostname & protocol for your site
twitter_username: pxbecko
github_username:  bsamartins

# Build settings
markdown: kramdown
